extract_job_runtime_start_timestamp_seconds:
  Category: extract
  MetricName: appstorestream_extract_job_runtime_start_timestamp_seconds
  Description: Extract start timestamp in seconds for Job
  Type: Gauge
extract_job_runtime_stop_timestamp_seconds:
  Category: extract
  MetricName: appstorestream_extract_job_runtime_stop_timestamp_seconds
  Description: Extract stop timestamp in seconds for Job
  Type: Gauge
extract_job_runtime_duration_seconds_total:
  Category: extract
  MetricName: appstorestream_extract_job_runtime_duration_seconds_total
  Description: Extract session duration total for Job
  Type: Counter
extract_job_request_session_count_total:
  Category: extract
  MetricName: appstorestream_extract_job_request_session_count_total
  Description: Extract session count for a Job
  Type: Counter
extract_job_request_count_total:
  Category: extract
  MetricName: appstorestream_extract_job_request_count_total
  Description: Extract request count for a Job
  Type: Counter
extract_job_request_per_second_ratio:
  Category: extract
  MetricName: appstorestream_extract_job_request_per_second_ratio
  Description: Extract session responses per second for Job
  Type: Gauge
extract_job_response_count_total:
  Category: extract
  MetricName: appstorestream_extract_job_response_count_total
  Description: Extract response count for a Job
  Type: Counter
extract_job_response_per_second_ratio:
  Category: extract
  MetricName: appstorestream_extract_job_response_per_second_ratio
  Description: Extract session responses per second for Job
  Type: Gauge
extract_job_response_average_latency_seconds:
  Category: extract
  MetricName: appstorestream_extract_job_response_average_latency_seconds
  Description: Extract session average response latency for Job
  Type: Gauge
extract_job_response_latency_seconds_total:
  Category: extract
  MetricName: appstorestream_extract_job_response_latency_seconds_total
  Description: Extract session  response latency total for Job
  Type: Gauge
extract_job_response_average_size_bytes:
  Category: extract
  MetricName: appstorestream_extract_job_response_average_size_bytes
  Description: Extract session average response size in bytes for Job
  Type: Gauge
extract_job_response_size_bytes_total:
  Category: extract
  MetricName: appstorestream_extract_job_response_size_bytes_total
  Description: Extract session total response size in bytes for Job
  Type: Counter
extract_job_success_failure_retries_total:
  Category: extract
  MetricName: appstorestream_extract_job_success_failure_retries_total
  Description: Extract session retry count for Job
  Type: Counter
extract_job_success_failure_errors_total:
  Category: extract
  MetricName: appstorestream_extract_job_success_failure_errors_total
  Description: Extract session error count for Job
  Type: Counter
extract_job_success_failure_request_failure_rate_ratio:
  Category: extract
  MetricName: appstorestream_extract_job_success_failure_request_failure_rate_ratio
  Description: Extract Session Errors / Requests for Job
  Type: Gauge
extract_job_success_failure_request_success_rate_ratio:
  Category: extract
  MetricName: appstorestream_extract_job_success_failure_request_success_rate_ratio
  Description: Extract Session 1 - Failure_Rate for Job
  Type: Gauge
extract_task_runtime_start_timestamp_seconds:
  Category: extract
  MetricName: appstorestream_extract_task_runtime_start_timestamp_seconds
  Description: Extract start timestamp in seconds for Task
  Type: Gauge
extract_task_runtime_stop_timestamp_seconds:
  Category: extract
  MetricName: appstorestream_extract_task_runtime_stop_timestamp_seconds
  Description: Extract stop timestamp in seconds for Task
  Type: Gauge
extract_task_runtime_duration_seconds:
  Category: extract
  MetricName: appstorestream_extract_task_runtime_duration_seconds
  Description: Extract session duration for Task
  Type: Gauge
extract_task_request_count_total:
  Category: extract
  MetricName: appstorestream_extract_task_request_count_total
  Description: Extract session request count for Task
  Type: Gauge
extract_task_request_per_second_ratio:
  Category: extract
  MetricName: appstorestream_extract_task_request_per_second_ratio
  Description: Extract session requests per second for Task
  Type: Gauge
extract_task_response_count_total:
  Category: extract
  MetricName: appstorestream_extract_task_response_count_total
  Description: Extract session response count for Task
  Type: Gauge
extract_task_response_per_second_ratio:
  Category: extract
  MetricName: appstorestream_extract_task_response_per_second_ratio
  Description: Extract session responses per second for Task
  Type: Gauge
extract_task_response_average_latency_seconds:
  Category: extract
  MetricName: appstorestream_extract_task_response_average_latency_seconds
  Description: Extract session average response latency for Task
  Type: Gauge
extract_task_response_latency_seconds_total:
  Category: extract
  MetricName: appstorestream_extract_task_response_latency_seconds_total
  Description: Extract session  response latency total for Task
  Type: Gauge
extract_task_response_average_size_bytes:
  Category: extract
  MetricName: appstorestream_extract_task_response_average_size_bytes
  Description: Extract session average response size in bytes for Task
  Type: Gauge
extract_task_response_size_bytes_total:
  Category: extract
  MetricName: appstorestream_extract_task_response_size_bytes_total
  Description: Extract session total response size in bytes for Task
  Type: Gauge
extract_task_success_failure_retries_total:
  Category: extract
  MetricName: appstorestream_extract_task_success_failure_retries_total
  Description: Extract session retry count for Task
  Type: Gauge
extract_task_success_failure_errors_total:
  Category: extract
  MetricName: appstorestream_extract_task_success_failure_errors_total
  Description: Extract session error count for Task
  Type: Gauge
extract_task_success_failure_client_errors_total:
  Category: extract
  MetricName: appstorestream_extract_task_success_failure_client_errors_total
  Description: Extract Session Client Error Count for Task
  Type: Gauge
extract_task_success_failure_server_errors_total:
  Category: extract
  MetricName: appstorestream_extract_task_success_failure_server_errors_total
  Description: Extract Session Server Error Count for Task
  Type: Gauge
extract_task_success_failure_redirect_errors_total:
  Category: extract
  MetricName: appstorestream_extract_task_success_failure_redirect_errors_total
  Description: Extract Session Redirect Error Count for Task
  Type: Gauge
extract_task_success_failure_unknown_errors_total:
  Category: extract
  MetricName: appstorestream_extract_task_success_failure_unknown_errors_total
  Description: Extract Session Unknown Error Count for Task
  Type: Gauge
extract_task_success_failure_request_failure_rate_ratio:
  Category: extract
  MetricName: appstorestream_extract_task_success_failure_request_failure_rate_ratio
  Description: Extract Session Errors / Requests for Task
  Type: Gauge
extract_task_success_failure_request_success_rate_ratio:
  Category: extract
  MetricName: appstorestream_extract_task_success_failure_request_success_rate_ratio
  Description: Extract Session 1 - Failure_Rate for Task
  Type: Gauge
extract_task_throttle_concurrency_efficiency_ratio:
  Category: extract
  MetricName: appstorestream_extract_task_throttle_concurrency_efficiency_ratio
  Description: Extract Session Average Latency / (Duration / Requests) for Task
  Type: Gauge
extract_task_throttle_average_latency_efficiency_ratio:
  Category: extract
  MetricName: appstorestream_extract_task_throttle_average_latency_efficiency_ratio
  Description: Extract Session Average Latency / Average Duration for Task
  Type: Gauge
extract_task_throttle_total_latency_efficiency_ratio:
  Category: extract
  MetricName: appstorestream_extract_task_throttle_total_latency_efficiency_ratio
  Description: Extract Session Total Latency  / Total Duration for Task
  Type: Gauge
