appstorestream_system_job_network_io_bytes:
  Description: System Network IO in bytes for Job
  Type: Counter
appstorestream_system_job_disk_io_bytes:
  Description: System Disk IO in bytes for Job
  Type: Counter
appstorestream_system_job_size_db_bytes:
  Description: System Database size in bytes for Job
  Type: Counter
appstorestream_system_job_cpu_average_pct_ratio:
  Description: System Average CPU Percent Utilized for Job
  Type: Gauge
appstorestream_system_job_memory_average_pct_ratio:
  Description: System Average Memory Percent Utilized for Job
  Type: Gauge
