appstorestream_transform_job_runtime_duration_seconds_total:
  Description: Transform Total Duration In Seconds for Job
  Type: Counter
appstorestream_transform_job_record_count_total:
  Description: Transform Total Record Count for Job
  Type: Counter
appstorestream_transform_job_record_size_bytes_total:
  Description: Transform Total Record Size In Bytes for Job
  Type: Counter
appstorestream_transform_job_record_per_second_ratio:
  Description: Transform Records Processed Per Second  for Job
  Type: Gauge
appstorestream_transform_job_success_failure_data_errors_total:
  Description: Transform Data Errors Encountered for Job
  Type: Counter
appstorestream_transform_job_success_failure_data_error_rate_ratio:
  Description: Transform Data Errors / Records for Job
  Type: Gauge
appstorestream_transform_job_success_failure_record_success_rate_ratio:
  Description: Transform 1 - Failure_Rate for Job
  Type: Gauge
appstorestream_transform_task_runtime_start_timestamp_seconds:
  Description: Transform Start Timestamp In Seconds for Task
  Type: Gauge
appstorestream_transform_task_runtime_stop_timestamp_seconds:
  Description: Transform Stop Timestamp In Seconds for Task
  Type: Gauge
appstorestream_transform_task_runtime_duration_seconds:
  Description: Transform Duration In Seconds for Task
  Type: Gauge
appstorestream_transform_task_record_count:
  Description: Transform Record Count for Task
  Type: Gauge
appstorestream_transform_task_record_average_size_bytes:
  Description: Transform Record Size In Bytes for Task
  Type: Gauge
appstorestream_transform_task_record_per_second_ratio:
  Description: Transform Records Processed Per Second  for Task
  Type: Gauge
appstorestream_transform_task_success_failure_data_errors_total:
  Description: Transform Data Errors Encountered During Task for Task
  Type: Gauge
appstorestream_transform_task_success_failure_data_error_rate_ratio:
  Description: Transform Data Errors / Records for Task
  Type: Gauge
appstorestream_transform_task_success_failure_record_success_rate_ratio:
  Description: Transform 1 - Failure_Rate for Task
  Type: Gauge
