CREATE TABLE IF NOT EXISTS appdata (
    app_id BIGINT NOT NULL PRIMARY KEY,
    app_name VARCHAR(255) NOT NULL,
    app_description TEXT NOT NULL,
    category_id INTEGER NOT NULL,
    category VARCHAR(64) NOT NULL,
    developer_id BIGINT NOT NULL,
    developer VARCHAR(255) NOT NULL,
    developer_url VARCHAR(255),
    seller_name VARCHAR(255) NOT NULL,
    seller_url VARCHAR(255),
    price DECIMAL(10,2) NOT NULL,
    rating_average DECIMAL(3,2) NOT NULL,
    rating_average_current_version DECIMAL(3,2) NOT NULL,
    rating_average_change_current_version DECIMAL(5,2),
    rating_average_pct_change_current_version DECIMAL(5,2),
    rating_count BIGINT NOT NULL,
    rating_count_current_version BIGINT NOT NULL,
    rating_count_per_day DECIMAL(10,2),
    rating_count_per_day_current_version DECIMAL(10,2),
    rating_count_pct_change_current_version DECIMAL(5,2),
    rating_count_pct_change_per_day_current_version DECIMAL(5,2),
    app_url VARCHAR(255),
    screenshot_urls JSON,
    release_date DATETIME NOT NULL,
    release_date_current_version DATETIME NOT NULL,
    app_version VARCHAR(8) NOT NULL,
    software_lifecycle_duration INTEGER
    time_since_last_release INTEGER,
    time_since_first_release INTEGER,
    extract_date DATETIME NOT NULL,
    INDEX idx_category_id (category_id),

);