#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Acquire                                                                    #
# Version    : 0.2.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/base.yaml                                                                   #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appvocai-acquire                                #
# ------------------------------------------------------------------------------------------------ #
# Created    : Saturday August 31st 2024 03:13:34 pm                                               #
# Modified   : Wednesday September 4th 2024 12:48:17 am                                            #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
# ------------------------------------------------------------------------------------------------ #
#                               SETUP CONFIG SECTION                                               #
# ------------------------------------------------------------------------------------------------ #
setup:
  database:
    tables:
      category:
        tablename: category
        filepath: data/base/categories.csv

# ------------------------------------------------------------------------------------------------ #
#                               EXTRACTOR CONFIG SECTION                                           #
# ------------------------------------------------------------------------------------------------ #
extractor:
  session_request_limit: 2000  # Maximum number of requests per session. Fixed for sessions
  retries: 3  # Retries allowed. Set and fixed for all jobs and sessions
  concurrency: 50 # Base concurrency. Reconfigured on a async request level
  timeout: 30 # Seconds
  history:
    max_history: 3600 # Seconds of history to maintain in the adapter history object.
  connector: # Config for aiohttp.TCPConnector
    use_dns_cache: True # Cache DNS to speed up connection
    ttl_dns_cache: 10  # Cache expiration in seconds. None means cached forever. By default 10 seconds (optional).
    limit: 200  # Maximum number of simultaneous connections
    limit_per_host: 0 # No limit
    enable_cleanup_closed: True # aiohttp additionally aborts underlining transport after 2 seconds.
    keepalive_timeout: 0 # Whether to keep the connection alive during the session
    force_close: True  # Close underlying sockets after connection releasing
    happy_eyeballs_delay: None # Seeconds to wait for a connection attempt to complete, before starting the next attempt in parallel
  session: # Config for aiohttp.ClientSession

    auto_decompress: True # Automatically decompress response body
    connector_owner: False  # Whether the session is responsible for closing the connector when the session itself is closed.
    trust_env: False # Whether to obtain proxy, ssl, and other config from environment variables.
    raise_for_status: True # Automatically call ClientResponse.raise_for_status() for each response


# ------------------------------------------------------------------------------------------------ #
#                                  TASK CONFIG SECTION                                             #
# ------------------------------------------------------------------------------------------------ #