#!/usr/bin/env bash
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Acquire                                                                    #
# Version    : 0.2.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/base.yaml                                                                   #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appvocai-acquire                                #
# ------------------------------------------------------------------------------------------------ #
# Created    : Friday July 19th 2024 04:22:54 am                                                   #
# Modified   : Thursday August 29th 2024 06:43:08 pm                                               #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
# ================================================================================================ #
#                                 BASE CONFIG FILE                                                 #
# ================================================================================================ #
# ------------------------------------------------------------------------------------------------ #
#                                DATABASE CONFIG SECTION                                           #
# ------------------------------------------------------------------------------------------------ #
database:
  dbname: appvocai
  ddl_directory: scripts/database/setup/tables
  project_data_filepath: scripts/database/setup/data/project.csv
  start: scripts/database/start.sh
  retries: 3
