#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppStoreStream: Apple App Data and Reviews, Delivered!                              #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/base.yaml                                                                   #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appstore-stream.git                             #
# ------------------------------------------------------------------------------------------------ #
# Created    : Friday July 19th 2024 04:22:54 am                                                   #
# Modified   : Saturday August 17th 2024 12:03:11 pm                                               #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
# ================================================================================================ #
#                                 BASE CONFIG FILE                                                 #
# ================================================================================================ #
# ------------------------------------------------------------------------------------------------ #
#                                DATABASE CONFIG SECTION                                           #
# ------------------------------------------------------------------------------------------------ #
database:
  dbname: appstorestream
  ddl_directory: scripts/database/setup/tables
  project_data_filepath: scripts/database/setup/data/project.csv
  start: scripts/database/start.sh
  retries: 3
# ------------------------------------------------------------------------------------------------ #
#                                METRICS CONFIG SECTION                                            #
# ------------------------------------------------------------------------------------------------ #
metrics:
  extract:
    appstorestream_extract_job_runtime_start_timestamp_seconds:
      Description: Extract start timestamp in seconds for Job
      Type: Gauge
    appstorestream_extract_job_runtime_stop_timestamp_seconds:
      Description: Extract stop timestamp in seconds for Job
      Type: Gauge
    appstorestream_extract_job_runtime_duration_seconds_total:
      Description: Extract session duration total for Job
      Type: Counter
    appstorestream_extract_job_request_session_count_total:
      Description: Extract session count for a Job
      Type: Counter
    appstorestream_extract_job_request_count_total:
      Description: Extract request count for a Job
      Type: Counter
    appstorestream_extract_job_request_per_second_ratio:
      Description: Extract session responses per second for Job
      Type: Gauge
    appstorestream_extract_job_response_count_total:
      Description: Extract response count for a Job
      Type: Counter
    appstorestream_extract_job_response_per_second_ratio:
      Description: Extract session responses per second for Job
      Type: Gauge
    appstorestream_extract_job_response_average_latency_seconds:
      Description: Extract session average response latency for Job
      Type: Gauge
    appstorestream_extract_job_response_latency_seconds_total:
      Description: Extract session  response latency total for Job
      Type: Gauge
    appstorestream_extract_job_response_average_size_bytes:
      Description: Extract session average response size in bytes for Job
      Type: Gauge
    appstorestream_extract_job_response_size_bytes_total:
      Description: Extract session total response size in bytes for Job
      Type: Counter
    appstorestream_extract_job_success_failure_retries_total:
      Description: Extract session retry count for Job
      Type: Counter
    appstorestream_extract_job_success_failure_errors_total:
      Description: Extract session error count for Job
      Type: Counter
    appstorestream_extract_job_success_failure_request_failure_rate_ratio:
      Description: Extract Session Errors / Requests for Job
      Type: Gauge
    appstorestream_extract_job_success_failure_request_success_rate_ratio:
      Description: Extract Session 1 - Failure_Rate for Job
      Type: Gauge
    appstorestream_extract_task_runtime_start_timestamp_seconds:
      Description: Extract start timestamp in seconds for Task
      Type: Gauge
    appstorestream_extract_task_runtime_stop_timestamp_seconds:
      Description: Extract stop timestamp in seconds for Task
      Type: Gauge
    appstorestream_extract_task_runtime_duration_seconds:
      Description: Extract session duration for Task
      Type: Gauge
    appstorestream_extract_task_request_count_total:
      Description: Extract session request count for Task
      Type: Gauge
    appstorestream_extract_task_request_per_second_ratio:
      Description: Extract session requests per second for Task
      Type: Gauge
    appstorestream_extract_task_response_count_total:
      Description: Extract session response count for Task
      Type: Gauge
    appstorestream_extract_task_response_per_second_ratio:
      Description: Extract session responses per second for Task
      Type: Gauge
    appstorestream_extract_task_response_average_latency_seconds:
      Description: Extract session average response latency for Task
      Type: Gauge
    appstorestream_extract_task_response_latency_seconds_total:
      Description: Extract session  response latency total for Task
      Type: Gauge
    appstorestream_extract_task_response_average_size_bytes:
      Description: Extract session average response size in bytes for Task
      Type: Gauge
    appstorestream_extract_task_response_size_bytes_total:
      Description: Extract session total response size in bytes for Task
      Type: Gauge
    appstorestream_extract_task_success_failure_retries_total:
      Description: Extract session retry count for Task
      Type: Gauge
    appstorestream_extract_task_success_failure_errors_total:
      Description: Extract session error count for Task
      Type: Gauge
    appstorestream_extract_task_success_failure_client_errors_total:
      Description: Extract Session Client Error Count for Task
      Type: Gauge
    appstorestream_extract_task_success_failure_server_errors_total:
      Description: Extract Session Server Error Count for Task
      Type: Gauge
    appstorestream_extract_task_success_failure_redirect_errors_total:
      Description: Extract Session Redirect Error Count for Task
      Type: Gauge
    appstorestream_extract_task_success_failure_unknown_errors_total:
      Description: Extract Session Unknown Error Count for Task
      Type: Gauge
    appstorestream_extract_task_success_failure_request_failure_rate_ratio:
      Description: Extract Session Errors / Requests for Task
      Type: Gauge
    appstorestream_extract_task_success_failure_request_success_rate_ratio:
      Description: Extract Session 1 - Failure_Rate for Task
      Type: Gauge
    appstorestream_extract_task_throttle_concurrency_efficiency_ratio:
      Description: Extract Session Average Latency / (Duration / Requests) for Task
      Type: Gauge
    appstorestream_extract_task_throttle_average_latency_efficiency_ratio:
      Description: Extract Session Average Latency / Average Duration for Task
      Type: Gauge
    appstorestream_extract_task_throttle_total_latency_efficiency_ratio:
      Description: Extract Session Total Latency  / Total Duration for Task
      Type: Gauge
  transform:
    appstorestream_transform_job_runtime_duration_seconds_total:
      Description: Transform Total Duration In Seconds for Job
      Type: Counter
    appstorestream_transform_job_record_count_total:
      Description: Transform Total Record Count for Job
      Type: Counter
    appstorestream_transform_job_record_size_bytes_total:
      Description: Transform Total Record Size In Bytes for Job
      Type: Counter
    appstorestream_transform_job_record_per_second_ratio:
      Description: Transform Records Processed Per Second  for Job
      Type: Gauge
    appstorestream_transform_job_success_failure_data_errors_total:
      Description: Transform Data Errors Encountered for Job
      Type: Counter
    appstorestream_transform_job_success_failure_data_error_rate_ratio:
      Description: Transform Data Errors / Records for Job
      Type: Gauge
    appstorestream_transform_job_success_failure_record_success_rate_ratio:
      Description: Transform 1 - Failure_Rate for Job
      Type: Gauge
    appstorestream_transform_task_runtime_start_timestamp_seconds:
      Description: Transform Start Timestamp In Seconds for Task
      Type: Gauge
    appstorestream_transform_task_runtime_stop_timestamp_seconds:
      Description: Transform Stop Timestamp In Seconds for Task
      Type: Gauge
    appstorestream_transform_task_runtime_duration_seconds:
      Description: Transform Duration In Seconds for Task
      Type: Gauge
    appstorestream_transform_task_record_count:
      Description: Transform Record Count for Task
      Type: Gauge
    appstorestream_transform_task_record_average_size_bytes:
      Description: Transform Record Size In Bytes for Task
      Type: Gauge
    appstorestream_transform_task_record_per_second_ratio:
      Description: Transform Records Processed Per Second  for Task
      Type: Gauge
    appstorestream_transform_task_success_failure_data_errors_total:
      Description: Transform Data Errors Encountered During Task for Task
      Type: Gauge
    appstorestream_transform_task_success_failure_data_error_rate_ratio:
      Description: Transform Data Errors / Records for Task
      Type: Gauge
    appstorestream_transform_task_success_failure_record_success_rate_ratio:
      Description: Transform 1 - Failure_Rate for Task
      Type: Gauge
  load:
    appstorestream_load_job_runtime_duration_seconds_total:
      Description: Load Total Duration In Seconds for Job
      Type: Counter
    appstorestream_load_job_record_count_total:
      Description: Load Total Load Record Count for Job
      Type: Counter
    appstorestream_load_job_record_average_size_bytes:
      Description: Load Load Record Count for Job
      Type: Gauge
    appstorestream_load_job_record_size_bytes_total:
      Description: Load Total Load Record Count for Job
      Type: Counter
    appstorestream_load_job_record_per_second_ratio:
      Description: Load Records Per Second for Job
      Type: Gauge
    appstorestream_load_task_runtime_start_timestamp_seconds:
      Description: Load Start Timestamp In Seconds for Task
      Type: Gauge
    appstorestream_load_task_runtime_stop_timestamp_seconds:
      Description: Load Stop Timestamp In Seconds for Task
      Type: Gauge
    appstorestream_load_task_runtime_duration_seconds:
      Description: Load Duration In Seconds for Task
      Type: Gauge
    appstorestream_load_task_record_count:
      Description: Load Load Record Count for Task
      Type: Gauge
    appstorestream_load_task_record_average_size_bytes:
      Description: Load Load Record Count for Task
      Type: Gauge
    appstorestream_load_task_record_size_bytes_total:
      Description: Load Total Load Record Count for Task
      Type: Gauge
    appstorestream_load_task_record_per_second_ratio:
      Description: Load Records Per Second for Task
      Type: Gauge
  system:
    appstorestream_system_job_network_io_bytes:
      Description: System Network IO in bytes for Job
      Type: Counter
    appstorestream_system_job_disk_io_bytes:
      Description: System Disk IO in bytes for Job
      Type: Counter
    appstorestream_system_job_size_db_bytes:
      Description: System Database size in bytes for Job
      Type: Counter
    appstorestream_system_job_cpu_average_pct_ratio:
      Description: System Average CPU Percent Utilized for Job
      Type: Gauge
    appstorestream_system_job_memory_average_pct_ratio:
      Description: System Average Memory Percent Utilized for Job
      Type: Gauge
