#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppStoreStream: Apple App Data and Reviews, Delivered!                              #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/base.yaml                                                                   #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appstore-stream.git                             #
# ------------------------------------------------------------------------------------------------ #
# Created    : Friday July 19th 2024 04:22:54 am                                                   #
# Modified   : Sunday July 28th 2024 08:10:32 pm                                                   #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
# ================================================================================================ #
#                                 BASE CONFIG FILE                                                 #
# ================================================================================================ #
# ------------------------------------------------------------------------------------------------ #
#                                SETUP CONFIG SECTION                                              #
# ------------------------------------------------------------------------------------------------ #
setup:
  database:
    ddl_directory: scripts/database/setup/tables

# ------------------------------------------------------------------------------------------------ #
#                              CIRCUIT BREAKER CONFIG SECTION                                      #
# ------------------------------------------------------------------------------------------------ #
circuit_breaker:
  closed:
    window_size: 300 # Size of window in seconds for closed state. Default 5 minutes.
    burnin_period: 300 # Seconds before monitoring starts.
    failure_rate_threshold: 0.5 # The proportion of failures over the window size that would trigger open state
  half_open:
    window_size: 600 # Size of window in seconds for half-open state. Default 10 minutes.
    failure_rate_threshold: 0.3
    delay: 2 # Number of seconds of delay in half-open state
  short_circuit_errors:
    window_size: 180 # Size of window in seconds for half-open state. Default 3 minutes.
    failure_rate_threshold: 0.9
  short_circuit_404s:
    window_size: 180 # Size of window in seconds for half-open state. Default 3 minutes.
    failure_rate_threshold: 0.7
  open:
    cooldown_period: 300 # Seconds before transitioning from open to half open state. Default 5 minutes.

# ------------------------------------------------------------------------------------------------ #
#                               HTTP REQUEST CONFIG SECTION                                        #
# ------------------------------------------------------------------------------------------------ #
request:
  generator:
    batch_size: 100
  asession:
    max_concurrency: 100
    retries: 3
    timeout: 30
  athrottle:
    min_rate: 1
    base_rate: 5
    max_rate: 100
    temperature: 0.5
    window_size: 10
    burn_in: 10

# ------------------------------------------------------------------------------------------------ #
#                                     LOGGING                                                      #
# ------------------------------------------------------------------------------------------------ #
logging:
  disable_existing_loggers: false
  formatters:
    console:
      datefmt: "%m/%d/%Y %I:%M:%S %p"
      format: "[%(asctime)s] [%(levelname)s] [%(name)s] [%(funcName)s] : %(message)s"
    file:
      datefmt: "%m/%d/%Y %I:%M:%S %p"
      format:
        "[%(asctime)s] [%(levelname)s] [%(name)s] [%(module)s] [%(funcName)s]
        : %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: console
      level: DEBUG
      stream: ext://sys.stderr
    file:
      backupCount: 0
      class: logging.handlers.TimedRotatingFileHandler
      filename: logs/appstore_stream.log
      formatter: file
      interval: 1
      level: DEBUG
      when: midnight
  root:
    handlers:
      - console
      - file
    level: DEBUG
  version: 1

# ------------------------------------------------------------------------------------------------ #
#                                 CLOUD STORAGE CONFIG                                             #
# ------------------------------------------------------------------------------------------------ #
cloud:
  aws_bucket: appvoc
  aws_appdata_folder: appdata
  aws_review_folder: reviews

# ------------------------------------------------------------------------------------------------ #
#                                     MONITOR CONFIG                                               #
# ------------------------------------------------------------------------------------------------ #
monitor:
  rate_update_interval: 15 # Number of seconds between rate updates
