#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppStoreStream: Apple App Data and Reviews, Delivered!                              #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/base.yaml                                                                   #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appstore-stream.git                             #
# ------------------------------------------------------------------------------------------------ #
# Created    : Friday July 19th 2024 04:22:54 am                                                   #
# Modified   : Friday August 2nd 2024 12:20:10 am                                                  #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
# ================================================================================================ #
#                                 BASE CONFIG FILE                                                 #
# ================================================================================================ #
# ------------------------------------------------------------------------------------------------ #
#                                DATABASE CONFIG SECTION                                           #
# ------------------------------------------------------------------------------------------------ #
database:
  dbname: appstorestream
  ddl_directory: scripts/database/setup/tables
  project_data_filepath: scripts/database/setup/data/project.csv
  start: scripts/database/start.sh
  retries: 3

# ------------------------------------------------------------------------------------------------ #
#                              CIRCUIT BREAKER CONFIG SECTION                                      #
# ------------------------------------------------------------------------------------------------ #
circuit_breaker:
  closed_burnin_period: 300
  closed_failure_rate_threshold: 0.5
  closed_window_size: 300
  half_open_delay: 2
  half_open_failure_rate_threshold: 0.3
  half_open_window_size: 600
  open_cooldown_period: 300
  short_circuit_404s_failure_rate_threshold: 0.7
  short_circuit_404s_window_size: 180
  short_circuit_errors_failure_rate_threshold: 0.9
  short_circuit_errors_window_size: 180
# ------------------------------------------------------------------------------------------------ #
#                        ASYNCHRONOUS SESSION CONFIG SECTION                                       #
# ------------------------------------------------------------------------------------------------ #
asession:
  max_concurrency: 100
  retries: 3
  timeout: 30
# ------------------------------------------------------------------------------------------------ #
#                    ASYNCHRONOUS HTTTP REQUEST THROTTLE CONFIG SECTION                            #
# ------------------------------------------------------------------------------------------------ #
athrottle:
  temperature: 0.5 # To distribute noise in the delay.
  concurrency: 100 # Same as max concurrency
  min_rate: 50 # 50 requests per second.
  max_rate: 1000 # 1000 requests per second.
  burnin:
    stage_length: 5 # Duration in minutes
    burnin_rate: 100 # 100 requests per second.
  exploration:
    stage_length: 5 # Maximum duration in minutes for exploration. If limit reached, reset and burnin phase restarted.
    threshold: 1.2  # System stable if process variable within 120% of baseline.
    window_size: 15 # Window size in # of sessions. With a batch size of 100, 15 sessions = 1500 requests.
    pause: 3 # Number of sessions between changes.
    heatup_factor: 50 # 50 requests per second increase per iteration during exploration.
    cooldown_factor: 10 # 10 requests per second decrease per iteration during exploration.
    min_rate: 50 # 50 requests per second or a delay of 2 seconds with batch size of 100
    max_rate: 1000  # 1000 requests per second or delay of 0.1 seconds with batch size of 100.
  exploitation:
    stage_length: 10 # Duration in minutes




# ------------------------------------------------------------------------------------------------ #
#                                     LOGGING                                                      #
# ------------------------------------------------------------------------------------------------ #
logging:
  disable_existing_loggers: false
  formatters:
    console:
      datefmt: "%m/%d/%Y %I:%M:%S %p"
      format: "[%(asctime)s] [%(levelname)s] [%(name)s] [%(funcName)s] : %(message)s"
    file:
      datefmt: "%m/%d/%Y %I:%M:%S %p"
      format:
        "[%(asctime)s] [%(levelname)s] [%(name)s] [%(module)s] [%(funcName)s]
        : %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: console
      level: DEBUG
      stream: ext://sys.stderr
    file:
      backupCount: 0
      class: logging.handlers.TimedRotatingFileHandler
      filename: logs/appstore_stream.log
      formatter: file
      interval: 1
      level: DEBUG
      when: midnight
  root:
    handlers:
      - console
      - file
    level: DEBUG
  version: 1

# ------------------------------------------------------------------------------------------------ #
#                                     MONITOR                                                      #
# ------------------------------------------------------------------------------------------------ #
monitor:
  prometheus_client_port: 8000
  prometheus_client_endpoint: http://localhost:8000/metrics