#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppStoreStream: Apple App Data and Reviews, Delivered!                              #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/base.yaml                                                                   #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appstore-stream.git                             #
# ------------------------------------------------------------------------------------------------ #
# Created    : Friday July 19th 2024 04:22:54 am                                                   #
# Modified   : Thursday August 1st 2024 10:44:20 am                                                #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
# ================================================================================================ #
#                                 BASE CONFIG FILE                                                 #
# ================================================================================================ #
# ------------------------------------------------------------------------------------------------ #
#                                DATABASE CONFIG SECTION                                           #
# ------------------------------------------------------------------------------------------------ #
database:
  dbname: appstorestream
  ddl_directory: scripts/database/setup/tables
  project_data_filepath: scripts/database/setup/data/project.csv
  start: scripts/database/start.sh
  retries: 3

# ------------------------------------------------------------------------------------------------ #
#                              CIRCUIT BREAKER CONFIG SECTION                                      #
# ------------------------------------------------------------------------------------------------ #
circuit_breaker:
  closed_burnin_period: 300
  closed_failure_rate_threshold: 0.5
  closed_window_size: 300
  half_open_delay: 2
  half_open_failure_rate_threshold: 0.3
  half_open_window_size: 600
  open_cooldown_period: 300
  short_circuit_404s_failure_rate_threshold: 0.7
  short_circuit_404s_window_size: 180
  short_circuit_errors_failure_rate_threshold: 0.9
  short_circuit_errors_window_size: 180
# ------------------------------------------------------------------------------------------------ #
#                        ASYNCHRONOUS SESSION CONFIG SECTION                                       #
# ------------------------------------------------------------------------------------------------ #
asession:
  max_concurrency: 100
  retries: 3
  timeout: 30
# ------------------------------------------------------------------------------------------------ #
#                    ASYNCHRONOUS HTTTP REQUEST THROTTLE CONFIG SECTION                            #
# ------------------------------------------------------------------------------------------------ #
athrottle:
  base_delay: 2 # With batch size of 100, this is 50 requests per second.
  session_window_size: 10 # Window size in # of sessions. With a batch size of 100, 10 sessions = 1000 requests.
  burnin_stage: 150 # Approximately 5 minutes
  exploration_threshold: 1.2  # 20% of baseline latency mean latency and cv latency
  exploitation_stage: 300 # Approximately 10 minutes.
  temperature: 0.3 # To distribute noise in the delay.
  min_delay: 0.2 # Corresponds with a rate of approx 500 requests per second..
  max_delay: 2  # Corresponds with a rate of approx. 50 requests per second.
  heatup_factor: 0.5 # Reduce delay by 0.5 seconds in exploration
  cooldown_factor: 0.1 # Increase delay by 0.1 seconds in exploration.


# ------------------------------------------------------------------------------------------------ #
#                                     LOGGING                                                      #
# ------------------------------------------------------------------------------------------------ #
logging:
  disable_existing_loggers: false
  formatters:
    console:
      datefmt: "%m/%d/%Y %I:%M:%S %p"
      format: "[%(asctime)s] [%(levelname)s] [%(name)s] [%(funcName)s] : %(message)s"
    file:
      datefmt: "%m/%d/%Y %I:%M:%S %p"
      format:
        "[%(asctime)s] [%(levelname)s] [%(name)s] [%(module)s] [%(funcName)s]
        : %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: console
      level: DEBUG
      stream: ext://sys.stderr
    file:
      backupCount: 0
      class: logging.handlers.TimedRotatingFileHandler
      filename: logs/appstore_stream.log
      formatter: file
      interval: 1
      level: DEBUG
      when: midnight
  root:
    handlers:
      - console
      - file
    level: DEBUG
  version: 1

# ------------------------------------------------------------------------------------------------ #
#                                     MONITOR                                                      #
# ------------------------------------------------------------------------------------------------ #
monitor:
  prometheus_client_port: 8000
  prometheus_client_endpoint: http://localhost:8000/metrics