#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppStoreStream: Apple App Data and Reviews, Delivered!                              #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/dev.yaml                                                                    #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appstore-stream.git                             #
# ------------------------------------------------------------------------------------------------ #
# Created    : Friday July 19th 2024 04:22:54 am                                                   #
# Modified   : Sunday August 4th 2024 11:21:21 pm                                                  #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
# ================================================================================================ #
#                                 DEV CONFIG FILE                                                 #
# ================================================================================================ #
# ------------------------------------------------------------------------------------------------ #
#                                DATABASE CONFIG SECTION                                           #
# ------------------------------------------------------------------------------------------------ #
database:
  dbname: appstorestream
  ddl_directory: scripts/database/setup/tables
  project_data_filepath: scripts/database/setup/data/project.csv
  start: scripts/database/start.sh
  retries: 3

# ------------------------------------------------------------------------------------------------ #
#                              CIRCUIT BREAKER CONFIG SECTION                                      #
# ------------------------------------------------------------------------------------------------ #
circuit_breaker:
  closed_burnin_period: 300
  closed_failure_rate_threshold: 0.5
  closed_window_size: 300
  half_open_delay: 2
  half_open_failure_rate_threshold: 0.3
  half_open_window_size: 600
  open_cooldown_period: 300
  short_circuit_404s_failure_rate_threshold: 0.7
  short_circuit_404s_window_size: 180
  short_circuit_errors_failure_rate_threshold: 0.9
  short_circuit_errors_window_size: 180
# ------------------------------------------------------------------------------------------------ #
#                        ASYNCHRONOUS SESSION CONFIG SECTION                                       #
# ------------------------------------------------------------------------------------------------ #
asession:
  max_concurrency: 100
  retries: 3
  timeout: 30
# ------------------------------------------------------------------------------------------------ #
#                    ASYNCHRONOUS HTTTP REQUEST THROTTLE CONFIG SECTION                            #
# ------------------------------------------------------------------------------------------------ #
athrottle:
  burnin_length: 300 # Number of seconds in stage
  explore_length: 300 # Number of seconds in stage
  exploit_length: 600 # Number of seconds in stage
  concurrency: 100
  min_rate: 50 # Default minimum rate
  max_rate: 1000 # Default maximum Rate
  rate: 50 # Default rate in requests per second for burnin stage
  temperature: 0.5 # Scale of random noise in delay.
  exploration_heatup_step_size: 10 # Number of requests per second to increase in heatup.
  exploration_cooldown_step_size: -5 # Number of requests per second to decrease in cooldown
  threshold: 0.2 # Threshold for proportion of change in cv and mean latency
  alpha: 0.05 # Significance for hypothesis testing

# ------------------------------------------------------------------------------------------------ #
#                                     LOGGING                                                      #
# ------------------------------------------------------------------------------------------------ #
logging:
  disable_existing_loggers: false
  formatters:
    console:
      datefmt: "%m/%d/%Y %I:%M:%S %p"
      format: "[%(asctime)s] [%(levelname)s] [%(name)s] [%(funcName)s] : %(message)s"
    file:
      datefmt: "%m/%d/%Y %I:%M:%S %p"
      format:
        "[%(asctime)s] [%(levelname)s] [%(name)s] [%(module)s] [%(funcName)s]
        : %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: console
      level: DEBUG
      stream: ext://sys.stderr
    file:
      backupCount: 0
      class: logging.handlers.TimedRotatingFileHandler
      filename: logs/dev/appstore_stream.log
      formatter: file
      interval: 1
      level: DEBUG
      when: midnight
  root:
    handlers:
      - console
      - file
    level: DEBUG
  version: 1

# ------------------------------------------------------------------------------------------------ #
#                                     MONITOR                                                      #
# ------------------------------------------------------------------------------------------------ #
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'appstore_stream'
    static_configs:
      - targets: ['appstore_stream_dev.com:8000']