#!/usr/bin/env bash
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Acquire                                                                    #
# Version    : 0.2.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/prod.yaml                                                                   #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appvocai-acquire                                #
# ------------------------------------------------------------------------------------------------ #
# Created    : Friday July 19th 2024 04:22:54 am                                                   #
# Modified   : Thursday August 29th 2024 06:42:53 pm                                               #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
# ================================================================================================ #
#                                 PROD CONFIG FILE                                                 #
# ================================================================================================ #
# ------------------------------------------------------------------------------------------------ #
#                                DATABASE CONFIG SECTION                                           #
# ------------------------------------------------------------------------------------------------ #
database:
  dbname: appvocai
  ddl_directory: scripts/database/setup/tables
  project_data_filepath: scripts/database/setup/data/project.csv
  start: scripts/database/start.sh
  retries: 3

# ------------------------------------------------------------------------------------------------ #
#                              CIRCUIT BREAKER CONFIG SECTION                                      #
# ------------------------------------------------------------------------------------------------ #
circuit_breaker:
  closed_burnin_period: 300
  closed_failure_rate_threshold: 0.5
  closed_window_size: 300
  half_open_delay: 2
  half_open_failure_rate_threshold: 0.3
  half_open_window_size: 600
  open_cooldown_period: 300
  short_circuit_404s_failure_rate_threshold: 0.7
  short_circuit_404s_window_size: 180
  short_circuit_errors_failure_rate_threshold: 0.9
  short_circuit_errors_window_size: 180
# ------------------------------------------------------------------------------------------------ #
#                        ASYNCHRONOUS SESSION CONFIG SECTION                                       #
# ------------------------------------------------------------------------------------------------ #
asession:
  retries: 3
  timeout: 30

# ------------------------------------------------------------------------------------------------ #
#                    ASYNCHRONOUS HTTP REQUEST RATE THROTTLE CONFIG SECTION                        #
# ------------------------------------------------------------------------------------------------ #
adapter:
  defaults: &adapter_defaults
    rate:
      base: 50 # base requests per second
      min: 20 # Minimum rate in requests per second
      max: 500 # Maximum rate in requests per second
    concurrency:
      base: 50 # Base concurrency
      min: 20 # Minimum concurrency
      max: 200 # Maximum concurrency
    window_size: 300
    temperature: 0.05

  baseline:
    <<: *adapter_defaults
    response_time: 300 # Seconds. Equates to 5 minute baseline period.
  explore_rate:
    <<: *adapter_defaults
    response_time: 3600 # 1 hour or until convergence
    step_increase: 50 # Additive rate increase per step
    step_decrease: 0.9 # Multiplicative rate during decrease per step
    step_response_time: 60 # 1 minute
    threshold: 1.2 # 120% of baseline mean and cv latency
  explore_concurrency:
    <<: *adapter_defaults
    response_time: 3600 # 1 hour or until convergence
    step_increase: 10 # Additive increase in concurrency each step
    step_decrease: 0.9 # Multiplicative decrease
    step_response_time: 60 # 2 minutes allowing system to adjust
    threshold: 1.2 # 120% of baeline mean and cv
  exploit:
    <<: *adapter_defaults
    response_time:  1800 # Recalibrate baseline every 30 minutes.
    k: 0.1 # A 10% change in mean latency would result in a 1% change in delay
    m: 0.05 # A 10% change in latency CV would result in a 0.5% change in delay



# ------------------------------------------------------------------------------------------------ #
#                                     LOGGING                                                      #
# ------------------------------------------------------------------------------------------------ #
logging:
  disable_existing_loggers: false
  formatters:
    console:
      datefmt: "%m/%d/%Y %I:%M:%S %p"
      format: "[%(asctime)s] [%(levelname)s] [%(name)s] [%(funcName)s] : %(message)s"
    file:
      datefmt: "%m/%d/%Y %I:%M:%S %p"
      format:
        "[%(asctime)s] [%(levelname)s] [%(name)s] [%(module)s] [%(funcName)s]
        : %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: console
      level: DEBUG
      stream: ext://sys.stderr
    file:
      backupCount: 0
      class: logging.handlers.TimedRotatingFileHandler
      filename: logs/prod/appstore_stream.log
      formatter: file
      interval: 1
      level: DEBUG
      when: midnight
  root:
    handlers:
      - console
      - file
    level: DEBUG
  version: 1
