#!/usr/bin/env bash
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Acquire                                                                    #
# Version    : 0.2.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/prometheus_test.yaml                                                        #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appvocai-acquire                                #
# ------------------------------------------------------------------------------------------------ #
# Created    : Friday July 19th 2024 04:22:54 am                                                   #
# Modified   : Thursday August 29th 2024 06:42:35 pm                                               #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
# ================================================================================================ #
#                                 PROMETHEUS TEST CONFIG FILE                                      #
# ================================================================================================ #
global:
  scrape_interval: 5m

scrape_configs:
  - job_name: 'appstore_stream_test'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['172.29.128.1:8020']