#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppStoreStream: Apple App Data and Reviews, Delivered!                              #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/test.yaml                                                                   #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appstore-stream.git                             #
# ------------------------------------------------------------------------------------------------ #
# Created    : Friday July 19th 2024 04:22:54 am                                                   #
# Modified   : Tuesday August 20th 2024 01:31:55 am                                                #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
# ================================================================================================ #
#                                 TEST CONFIG FILE                                                 #
# ================================================================================================ #
# ------------------------------------------------------------------------------------------------ #
#                                DATABASE CONFIG SECTION                                           #
# ------------------------------------------------------------------------------------------------ #
database:
  dbname: appstorestream
  ddl_directory: scripts/database/setup/tables
  project_data_filepath: scripts/database/setup/data/project.csv
  start: scripts/database/start.sh
  retries: 3

# ------------------------------------------------------------------------------------------------ #
#                              CIRCUIT BREAKER CONFIG SECTION                                      #
# ------------------------------------------------------------------------------------------------ #
circuit_breaker:
  closed_burnin_period: 300
  closed_failure_rate_threshold: 0.5
  closed_window_size: 300
  half_open_delay: 2
  half_open_failure_rate_threshold: 0.3
  half_open_window_size: 600
  open_cooldown_period: 300
  short_circuit_404s_failure_rate_threshold: 0.7
  short_circuit_404s_window_size: 180
  short_circuit_errors_failure_rate_threshold: 0.9
  short_circuit_errors_window_size: 180
# ------------------------------------------------------------------------------------------------ #
#                        ASYNCHRONOUS SESSION CONFIG SECTION                                       #
# ------------------------------------------------------------------------------------------------ #
asession:
  retries: 3
  timeout: 30
# ------------------------------------------------------------------------------------------------ #
#                    ASYNCHRONOUS HTTP REQUEST RATE THROTTLE CONFIG SECTION                        #
# ------------------------------------------------------------------------------------------------ #
athrottle:
  temperature: 0.2 # Scale parameter for random noise injection into delay
  warmup:
    duration: 300 # Seconds. Equates to 5 minute warmup period.
    concurrency: 100 # number of concurrent requests during baseline.
    delay: 1 # Delay between asynchronous requests in seconds.
  cook:
    duration:  3600 # Recalibrate baseline every hour.
    window_size: 60 # Window size in seconds.
    k: 0.1 # A 10% change in mean latency would result in a 1% change in delay
    m: 0.05 # A 10% change in latency CV would result in a 0.5% change in delay
    min_delay: 0 # Minimum delay between asynchronous requests in seconds
    max_delay: 2 # Maximum delay between asynchronous requests in seconds

# ------------------------------------------------------------------------------------------------ #
#                    ASYNCHRONOUS HTTP REQUEST CONCURRENCY CONFIG SECTION                          #
# ------------------------------------------------------------------------------------------------ #
concurrency:
  warmup: # Determines ideal concurrency based on throughput
    frequency: 3600 # Recalibrate baseline concurrency each hour.
    steps: 20 # Number of different concurrency values to evaluate
    step_duration: 60 # Evaluate throughput for each concurrency step for a 1 minutes.
    step_start: 50 # Concurrency at start step
    step_stop: 1000 # Concurrency at final step
  cook: # Adjusts concurrency based variation
    window_size: 60 # Window size in seconds.
    k: 0.1 # A 10% change in mean throughput would result in a 1% change in concurrency
    m: 0.05 # A 10% change in throughput CV would result in a 0.5% change in concurrency
    min_concurrency: 10 # Minimum concurrency value
    max_concurrency: 1000 # Maximum concurrency value




# ------------------------------------------------------------------------------------------------ #
#                                     LOGGING                                                      #
# ------------------------------------------------------------------------------------------------ #
logging:
  disable_existing_loggers: false
  formatters:
    console:
      datefmt: "%m/%d/%Y %I:%M:%S %p"
      format: "[%(asctime)s] [%(levelname)s] [%(name)s] [%(funcName)s] : %(message)s"
    file:
      datefmt: "%m/%d/%Y %I:%M:%S %p"
      format:
        "[%(asctime)s] [%(levelname)s] [%(name)s] [%(module)s] [%(funcName)s]
        : %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: console
      level: DEBUG
      stream: ext://sys.stderr
    file:
      backupCount: 0
      class: logging.handlers.TimedRotatingFileHandler
      filename: logs/test/appstore_stream.log
      formatter: file
      interval: 1
      level: DEBUG
      when: midnight
  root:
    handlers:
      - console
      - file
    level: DEBUG
  version: 1
