#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppStoreStream: Apple App Data and Reviews, Delivered!                              #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/test.yaml                                                                   #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appstore-stream.git                             #
# ------------------------------------------------------------------------------------------------ #
# Created    : Friday July 19th 2024 04:22:54 am                                                   #
# Modified   : Friday August 23rd 2024 07:43:48 pm                                                 #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
# ================================================================================================ #
#                                 TEST CONFIG FILE                                                 #
# ================================================================================================ #
# ------------------------------------------------------------------------------------------------ #
#                                DATABASE CONFIG SECTION                                           #
# ------------------------------------------------------------------------------------------------ #
database:
  dbname: appstorestream
  ddl_directory: scripts/database/setup/tables
  project_data_filepath: scripts/database/setup/data/project.csv
  start: scripts/database/start.sh
  retries: 3

# ------------------------------------------------------------------------------------------------ #
#                              CIRCUIT BREAKER CONFIG SECTION                                      #
# ------------------------------------------------------------------------------------------------ #
circuit_breaker:
  closed_burnin_period: 300
  closed_failure_rate_threshold: 0.5
  closed_window_size: 300
  half_open_delay: 2
  half_open_failure_rate_threshold: 0.3
  half_open_window_size: 600
  open_cooldown_period: 300
  short_circuit_404s_failure_rate_threshold: 0.7
  short_circuit_404s_window_size: 180
  short_circuit_errors_failure_rate_threshold: 0.9
  short_circuit_errors_window_size: 180
# ------------------------------------------------------------------------------------------------ #
#                        ASYNCHRONOUS SESSION CONFIG SECTION                                       #
# ------------------------------------------------------------------------------------------------ #
asession:
  retries: 3
  timeout: 30
# ------------------------------------------------------------------------------------------------ #
#                    ASYNCHRONOUS HTTP REQUEST RATE THROTTLE CONFIG SECTION                        #
# ------------------------------------------------------------------------------------------------ #
adapter:
  baseline:
    duration: 5 # Seconds. Equates to 5 minute baseline period.
    concurrency: 50 # number of concurrent requests during baseline.
    window_size: 300 # Five minute window
    temperature: 0.05 # Scale parameter for random noise injection into delay
    rate: 50 # 50 rps
    min_rate: 50 # 50 Requests per second
    max_rate: 500 # 500 requests per second
  explore_rate:
    duration: 5 # 1 hour or until convergence
    concurrency: 50 # number of concurrent requests during baseline.
    step_increase: 50 # Additive rate increase per step
    step_decrease: 0.8 # 80% Multiplicative rate during decrease per step
    step_duration: .1 # 1 minute
    window_size: 300 # 5 Minutes
    threshold: 1.2 # 120% of baseline mean and cv latency
    temperature: 0.05 # Scale parameter for random noise injection into delay
    rate: 50 # 50 rps
    min_rate: 50 # 50 Requests per second
    max_rate: 500 # 500 requests per second
  explore_concurrency:
    duration: 5 # 1 hour or until convergence
    min_rate: 50 # 50 Requests per second
    max_rate: 500 # 500 requests per second
    concurrency: 50 # starting concurrency
    min_concurrency: 50 # Minimum concurrency
    max_concurrency: 200 # Maximum concurrency
    step_increase: 10 # Additive increase in concurrency each step
    step_decrease: 0.2 # 20% Multiplicative concurrency decrease per step
    step_duration: .1 # 2 minutes allowing system to adjust
    window_size: 300 # 5 minutes
    threshold: 1.2 # 120% of baeline mean and cv
    temperature: 0.05 # Scale parameter for random noise injection into delay
  exploit:
    duration:  5 # Recalibrate baseline every 30 minutes.
    window_size: 300 # Window size in seconds.
    k: 0.1 # A 10% change in mean latency would result in a 1% change in delay
    m: 0.05 # A 10% change in latency CV would result in a 0.5% change in delay
    min_rate: 50 # Minimum requests per second
    max_rate: 500 # Maximum requests per second



# ------------------------------------------------------------------------------------------------ #
#                                     LOGGING                                                      #
# ------------------------------------------------------------------------------------------------ #
logging:
  disable_existing_loggers: false
  formatters:
    console:
      datefmt: "%m/%d/%Y %I:%M:%S %p"
      format: "[%(asctime)s] [%(levelname)s] [%(name)s] [%(funcName)s] : %(message)s"
    file:
      datefmt: "%m/%d/%Y %I:%M:%S %p"
      format:
        "[%(asctime)s] [%(levelname)s] [%(name)s] [%(module)s] [%(funcName)s]
        : %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: console
      level: DEBUG
      stream: ext://sys.stderr
    file:
      backupCount: 0
      class: logging.handlers.TimedRotatingFileHandler
      filename: logs/test/appstore_stream.log
      formatter: file
      interval: 1
      level: DEBUG
      when: midnight
  root:
    handlers:
      - console
      - file
    level: DEBUG
  version: 1
