#!/usr/bin/env bash
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Acquire                                                                    #
# Version    : 0.2.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/test.yaml                                                                   #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appvocai-acquire                                #
# ------------------------------------------------------------------------------------------------ #
# Created    : Friday July 19th 2024 04:22:54 am                                                   #
# Modified   : Tuesday September 3rd 2024 07:01:36 am                                              #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
# ================================================================================================ #
#                                 TEST CONFIG FILE                                                 #
# ================================================================================================ #
# ------------------------------------------------------------------------------------------------ #
#                                DATABASE CONFIG SECTION                                           #
# ------------------------------------------------------------------------------------------------ #
database:
  dbname: appvocai
  ddl_directory: scripts/database/setup/tables
  start: scripts/database/start.sh
  retries: 3
  setup_data:
    categories: setup/categories.csv
    projects: setup/projects.csv


# ------------------------------------------------------------------------------------------------ #
#                              CIRCUIT BREAKER CONFIG SECTION                                      #
# ------------------------------------------------------------------------------------------------ #
circuit_breaker:
  closed_burnin_period: 300
  closed_failure_rate_threshold: 0.5
  closed_window_size: 300
  half_open_delay: 2
  half_open_failure_rate_threshold: 0.3
  half_open_window_size: 600
  open_cooldown_period: 300
  short_circuit_404s_failure_rate_threshold: 0.7
  short_circuit_404s_window_size: 180
  short_circuit_errors_failure_rate_threshold: 0.9
  short_circuit_errors_window_size: 180

# ------------------------------------------------------------------------------------------------ #
#                    ASYNCHRONOUS HTTP REQUEST RATE THROTTLE CONFIG SECTION                        #
# ------------------------------------------------------------------------------------------------ #
adapter:
  defaults: &session_defaults
    rate:
      base: 50 # base requests per second
      min: 10 # Minimum rate in requests per second
      max: 500 # Maximum rate in requests per second
    concurrency:
      base: 50 # Base concurrency
      min: 50 # Minimum concurrency
      max: 200 # Maximum concurrency
    window_size: 300
    temperature: 0.1

  baseline:
    <<: *session_defaults
    response_time: 2 # Seconds. Equates to 5 minute baseline period.
  explore_rate:
    <<: *session_defaults
    response_time: 2 # 1 hour or until convergence
    step_increase: 50 # Additive rate increase per step
    step_decrease: 0.9 # Multiplicative rate during decrease per step
    step_response_time: 1 # 1 minute
    threshold: 1.2 # 120% of baseline mean and cv latency
  explore_concurrency:
    <<: *session_defaults
    response_time: 2 # 1 hour or until convergence
    step_increase: 10 # Additive increase in concurrency each step
    step_decrease: 0.9 # Multiplicative decrease
    step_response_time: .1 # 2 minutes allowing system to adjust
    threshold: 1.2 # 120% of baeline mean and cv
  exploit:
    <<: *session_defaults
    response_time:  5 # Recalibrate baseline every 30 minutes.
    k: 0.1 # A 10% change in mean latency would result in a 1% change in delay
    m: 0.05 # A 10% change in latency CV would result in a 0.5% change in delay

# ------------------------------------------------------------------------------------------------ #
#                                     LOGGING                                                      #
# ------------------------------------------------------------------------------------------------ #
logging:
  disable_existing_loggers: false
  formatters:
    console:
      datefmt: "%m/%d/%Y %I:%M:%S %p"
      format: "[%(asctime)s] [%(levelname)s] [%(name)s] [%(funcName)s] : %(message)s"
    file:
      datefmt: "%m/%d/%Y %I:%M:%S %p"
      format:
        "[%(asctime)s] [%(levelname)s] [%(name)s] [%(module)s] [%(funcName)s]
        : %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: console
      level: DEBUG
      stream: ext://sys.stderr
    file:
      backupCount: 0
      class: logging.handlers.TimedRotatingFileHandler
      filename: logs/test/appstore_stream.log
      formatter: file
      interval: 1
      level: DEBUG
      when: midnight
  root:
    handlers:
      - console
      - file
    level: DEBUG
  version: 1
