CREATE TABLE appdata (
    app_id BIGINT NOT NULL PRIMARY KEY,
    app_name VARCHAR(255) NOT NULL,
    app_censored_name VARCHAR(255),
    bundle_id VARCHAR(255),
    description TEXT NOT NULL,
    category_id INTEGER NOT NULL,
    category VARCHAR(128) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    currency VARCHAR(8) NOT NULL,
    average_user_rating INTEGER NOT NULL,
    average_user_rating_current_version INTEGER NOT NULL,
    user_rating_count INTEGER NOT NULL,
    user_rating_current_version INTEGER NOT NULL,
    developer_id BIGINT NOT NULL,
    developer_name VARCHAR(255) NOT NULL,
    developer_view_url VARCHAR(255),
    seller_name VARCHAR(255) NOT NULL,
    seller_url VARCHAR(255),
    app_content_rating VARCHAR(255) NOT NULL,
    content_advisory_rating VARCHAR(255) NOT NULL,
    file_size_bytes VARCHAR(255),
    minimum_os_version VARCHAR(255),
    version VARCHAR(8) NOT NULL,
    release_date DATETIME NOT NULL,
    release_notes LONGTEXT NOT NULL,
    current_version_release_date DATETIME NOT NULL,
    artwork_url100 VARCHAR(255),
    app_view_url VARCHAR(255),
    artwork_url512 VARCHAR(255),
    artwork_url60 VARCHAR(255),
    extract_date DATETIME NOT NULL,
    UNIQUE (app_id) -- Assuming you want app_id to be unique as well
);
